language: node_js
node_js:
- '0.11'
sudo: false
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: CJD2540lhbdWKkKv4nK9DH0x4+/sRM0HiPLB6sDkmpuMMcerCv8juZ8A1sceky0Lp92INnJA7feJ9UwXqwIYFdHzpInhkgzhhheOB74gIkjpaIoabrO9UyMXqPCO1+hG2bOYXYVc50dCvwI37K5Tqs7bCqWTC/eAW4dZfuntP9Y=
notifications:
  email: false
  slack:
    secure: JEgKC3OtxGyjrBt7LDNmB5+bwC7n4BGFUYMTGvxgj2HzwJjnAL9sJpc31guBm9JCnnDSOdowuE7K6eLuvvXwWmpd/j1Um5Fk1F10+Y9SAliDh7/LrWOKAjpLbsvZikpwE9QjUheXEd76bdtLbznSmSF5wp9fouSULFremXFrI0U=
