language: node_js
node_js:
- '0.11'
sudo: false
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: k2UROr7uWIys6i3oCLqMh8jnUIlYwkf+40abUwZvTu7V7EZhkp1sI0aQFpUO98BUIH2WPDKJi1hV6nVhFk5SMUstunCVyBS/EcKQab1zHpJUc92IfbaVejPg44rIcmnqlXvst2xx5k8mJUtyMQk5D8zBKLxSzyprnORGbLxyWlw=
notifications:
  email: false
  slack:
    secure: GRH2EgxcxM/LEOEeBnofllzXoHTttN0ZN4dSEdH5g18XA6efcFuGRmaUXbzViTB+U9e0e+3O2t2rKRyrlYsDgni9Mm/Za6+JOaoiGxhSwAFDiPwUKXQCgUrskhRxEMJdTwtp6bTRfkJGNUt0DTWdp2xFq3JLIs69m+lIyWwDqXY=
